# Generated by Django 4.0.5 on 2022-06-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='raiting',
            new_name='rating',
        ),
    ]
