# Generated by Django 4.0.5 on 2022-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_movie_director_alter_movie_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Квентин Торантино', max_length=100),
        ),
    ]
