# Generated by Django 4.0.5 on 2022-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='direktor_mail',
            field=models.EmailField(default='no@gmail.com', max_length=254),
        ),
    ]
