# Generated by Django 4.0.5 on 2022-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_movie_direktor_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Торантино', max_length=100)),
                ('last_name', models.CharField(default='Квентин', max_length=100)),
                ('direktor_mail', models.EmailField(default='no@gmail.com', max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='direktor_mail',
        ),
    ]
