# Generated by Django 4.0.5 on 2022-06-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='direktor_mail',
        ),
        migrations.AddField(
            model_name='director',
            name='director_mail',
            field=models.EmailField(default='no@gmail.com', max_length=254),
        ),
    ]
