# Generated by Django 4.0.5 on 2022-06-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0021_actor_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='slug',
        ),
    ]
